input_channel: 3

depth_multiple: 1.0
width_multiple: 1.0

backbone:
    # [repeat, module, args]
    [
        # Conv argument: [out_channel, kernel_size, stride, padding_size]
        # if padding_size is not given or null, the padding_size will be auto adjusted as padding='SAME' in TensorFlow
        [1, Conv, [16, 3, 2, null, 1, "HardSwish"]],
        # k t c SE HS s
        [1, InvertedResidualv3, [3, 1, 16, 0, 0, 1]],
        [1, InvertedResidualv3, [3, 4, 24, 0, 0, 2]], # 2-P2/4, 24 # stride 1 for cifar, 2 for others
        [1, InvertedResidualv3, [3, 3, 24, 0, 0, 1]],     
        [1, InvertedResidualv3, [5, 3, 40, 1, 0, 2]], # 4-P3/8, 40
        [1, InvertedResidualv3, [5, 3, 40, 1, 0, 1]],     
        [1, InvertedResidualv3, [5, 3, 40, 1, 0, 1]],     
        [1, InvertedResidualv3, [3, 6, 80, 0, 1, 2]], # 7-P4/16, 80   
        [1, InvertedResidualv3, [3, 2.5, 80, 0, 1, 1]],     
        [1, InvertedResidualv3, [3, 2.3, 80, 0, 1, 1]],     
        [1, InvertedResidualv3, [3, 2.3, 80, 0, 1, 1]],     
        [1, InvertedResidualv3, [3, 6, 112, 1, 1, 1]],     
        [1, InvertedResidualv3, [3, 6, 112, 1, 1, 1]], # 12 -P5/32, 112 
        [1, InvertedResidualv3, [5, 6, 160, 1, 1, 2]],    
        [1, InvertedResidualv3, [5, 6, 160, 1, 1, 1]],     
        [1, InvertedResidualv3, [5, 6, 160, 1, 1, 1]],     
        [1, Conv, [960, 1, 1]],
        [1, GlobalAvgPool, []],
        [1, Conv, [1280, 1, 1]],
        [1, Flatten, []],
        [1, Linear, [6]]
    ]
